version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "hearot"
    reviewers:
      - "hearot"
    commit-message:
      prefix: "chore(dependencies): update "
      include: "scope"
    labels:
      - "dependencies"
